name: Run NPM Build and Commit Changes

on:
  repository_dispatch:
    types: [trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Использование вашего Personal Access Token для доступа к репозиторию

      # - name: Set up Node.js
        # uses: actions/setup-node@v3
        # with:
          # node-version: '21.5.0'  # Установка нужной версии Node.js

      # - name: Install Dependencies
        # run: npm install

      - name: Create Date File
        run: echo "// Placeholder for TypeScript code" > test$(date +%Y%m%d%H%M%S).ts
        # Создание файла с датой в имени

      - name: Commit and Push Date File
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "Automated Builder"
          git add test$(date +%Y%m%d).ts
          git commit -m "Add new date file test$(date +%Y%m%d).ts"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # Установка переменной окружения GITHUB_TOKEN для использования в командах Git
